export const data = [
  {
    id: 1,
    date: '03/09/2022',
    factNum: 455,
    cant: 20,
    name: 'Niyelith ',
    middlename: 'undefined',
    surname: 'Salamanca',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'CEREMONIAL',
    costumeName: 'togas',
    gender: 'undefined',
    price: 112000,
    total: 2240000,
    payment: 1340000,
    debt: 900000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 0,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'Abono de 500000 ver factura 720',
    progress: 0,
  },
  {
    id: 2,
    date: '10/09/2022',
    factNum: 456,
    cant: 1,
    name: 'Maria  ',
    middlename: 'Claudia',
    surname: 'Vidal',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Encanto',
    gender: 'Girl',
    price: 220000,
    total: 220000,
    payment: 100000,
    debt: 120000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 0,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 3,
    date: '10/09/2022',
    factNum: 457,
    cant: 1,
    name: 'Sandra ',
    middlename: 'undefined',
    surname: 'Santacruz',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'THOR',
    gender: 'Woman',
    price: 330000,
    total: 330000,
    payment: 100000,
    debt: 230000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3177747909,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 4,
    date: '12/09/2022',
    factNum: 458,
    cant: 1,
    name: 'Natalia',
    middlename: 'undefined',
    surname: 'Ruiz',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'CEREMONIAL',
    costumeName: 'Vestido Palo de Rosa',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 100000,
    debt: 80000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '26/09/2022',
    size: 'undefined',
    phone: 3107460222,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 5,
    date: '15/09/2022',
    factNum: 459,
    cant: 1,
    name: 'yensy',
    middlename: 'undefined',
    surname: 'marin',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'toy story',
    gender: 'Boy',
    price: 0,
    total: 0,
    payment: 0,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3103754012,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 6,
    date: '16/09/2022',
    factNum: 460,
    cant: 1,
    name: 'Andrea',
    middlename: 'undefined',
    surname: 'Luna',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Anya Forger',
    gender: 'Girl',
    price: 170000,
    total: 170000,
    payment: 100000,
    debt: 70000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '25/10/2022',
    size: 'undefined',
    phone: 3246832390,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 7,
    date: '17/09/2022',
    factNum: 461,
    cant: 1,
    name: 'Yolanda',
    middlename: 'undefined',
    surname: 'Mamian',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'CEREMONIAL',
    costumeName: ' vestido de bautizo',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 0,
    debt: 180000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '21/09/2022',
    size: 'undefined',
    phone: 3154737714,
    status: 'DELIVERED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 8,
    date: '17/09/2022',
    factNum: 462,
    cant: 1,
    name: 'Guillermo',
    middlename: 'undefined',
    surname: 'Narvaez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Principe Bella y Bestia',
    gender: 'Boy',
    price: 160000,
    total: 160000,
    payment: 100000,
    debt: 60000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '25/10/2022',
    size: 'undefined',
    phone: 3244576867,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 9,
    date: '17/09/2022',
    factNum: 463,
    cant: 1,
    name: 'Guillermo',
    middlename: 'undefined',
    surname: 'Narvaez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'traje antiguo ',
    gender: 'Man',
    price: 510000,
    total: 510000,
    payment: 140000,
    debt: 370000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '########',
    size: 'undefined',
    phone: 3244576867,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 10,
    date: '17/09/2022',
    factNum: 463,
    cant: 1,
    name: 'Guillermo',
    middlename: 'undefined',
    surname: 'Narvaez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'traje antiguo ',
    gender: 'Boy',
    price: 170000,
    total: 170000,
    payment: 140000,
    debt: 30000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '########',
    size: 'undefined',
    phone: 3244576867,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 11,
    date: '28/09/2022',
    factNum: 464,
    cant: 1,
    name: 'Maria ',
    middlename: 'Virginia ',
    surname: 'Hormaza',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Invierno',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 86667,
    debt: 93333,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 3122998800,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 12,
    date: '28/09/2022',
    factNum: 464,
    cant: 1,
    name: 'Maria ',
    middlename: 'Virginia ',
    surname: 'Hormaza',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Verano',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 86667,
    debt: 93333,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 3122998800,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 13,
    date: '28/09/2022',
    factNum: 464,
    cant: 1,
    name: 'Maria ',
    middlename: 'Virginia ',
    surname: 'Hormaza',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Thor',
    gender: 'Girl',
    price: 300000,
    total: 300000,
    payment: 86667,
    debt: 213333,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 3122998800,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 14,
    date: '28/09/2022',
    factNum: 465,
    cant: 1,
    name: 'Elizabeth',
    middlename: 'undefined',
    surname: 'Lopez',
    lastsurname: 'B',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Principe Hindu',
    gender: 'Boy',
    price: 195000,
    total: 195000,
    payment: 100000,
    debt: 95000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3235048389,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 15,
    date: '28/09/2022',
    factNum: 466,
    cant: 14,
    name: 'Jorge',
    middlename: 'undefined',
    surname: 'Ñañez',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Encanto',
    gender: 'Girl',
    price: 82142,
    total: 1149988,
    payment: 0,
    debt: 1149988,
    rentValue: 0,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3148896250,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'Sin cancelar',
    progress: 0,
  },
  {
    id: 16,
    date: '02/09/2022',
    factNum: 529,
    cant: 0,
    name: 'VIVIANA',
    middlename: 'undefined',
    surname: 'PEREZ',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'BLANCA NIEVES',
    gender: 'Girl',
    price: 160000,
    total: 0,
    payment: 55000,
    debt: -55000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '22/10/2022',
    size: 'undefined',
    phone: 3148321524,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 17,
    date: '03/09/2022',
    factNum: 530,
    cant: 1,
    name: 'PATRICIA',
    middlename: 'undefined',
    surname: 'DIAZ',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'PRINCIPE AZUL',
    gender: 'Boy',
    price: 165000,
    total: 165000,
    payment: 100000,
    debt: 65000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '24/10/2022',
    size: 'undefined',
    phone: 3137894382,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'undefined',
    description: '1 AÑO',
    progress: 0,
  },
  {
    id: 18,
    date: '19/09/2022',
    factNum: 532,
    cant: 1,
    name: 'Oveimar',
    middlename: 'undefined',
    surname: 'Gomez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Blanca Nieves',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 100000,
    debt: 80000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '24/10/2022',
    size: 'undefined',
    phone: 3136206309,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description:
      'capa con cuello, vestido corto, enagua, tutu con dobladillo redondo, balaca',
    progress: 0,
  },
  {
    id: 19,
    date: '19/09/2022',
    factNum: 533,
    cant: 1,
    name: 'Anyi',
    middlename: 'Daniela',
    surname: 'Meneses',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Harley Quinn',
    gender: 'Girl',
    price: 160000,
    total: 160000,
    payment: 100000,
    debt: 60000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '27/10/2022',
    size: 'undefined',
    phone: 3177050215,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Tutú',
    progress: 0,
  },
  {
    id: 20,
    date: '19/09/2022',
    factNum: 534,
    cant: 1,
    name: 'Norby',
    middlename: 'undefined',
    surname: 'Montero',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Zorro',
    gender: 'Boy',
    price: 175000,
    total: 175000,
    payment: 50000,
    debt: 125000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3177050215,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 21,
    date: '19/09/2022',
    factNum: 534,
    cant: 1,
    name: 'Norby',
    middlename: 'undefined',
    surname: 'Montero',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Spiderman',
    gender: 'Boy',
    price: 175000,
    total: 175000,
    payment: 50000,
    debt: 125000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3177050215,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 22,
    date: '19/09/2022',
    factNum: 534,
    cant: 1,
    name: 'Norby',
    middlename: 'undefined',
    surname: 'Montero',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Unicornio',
    gender: 'Girl',
    price: 220000,
    total: 220000,
    payment: 50000,
    debt: 170000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3177050215,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 23,
    date: '19/09/2022',
    factNum: 535,
    cant: 1,
    name: 'Arelys',
    middlename: 'undefined',
    surname: 'Guzman',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Spiderman',
    gender: 'Boy',
    price: 135000,
    total: 135000,
    payment: 50000,
    debt: 85000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3136927791,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: "'3113328870'",
    progress: 0,
  },
  {
    id: 24,
    date: '21/09/2022',
    factNum: 536,
    cant: 2,
    name: 'Doris',
    middlename: 'undefined',
    surname: 'Velasco',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'undefined',
    gender: 'Girl',
    price: 50000,
    total: 100000,
    payment: 100000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3152414845,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 25,
    date: '24/09/2022',
    factNum: 537,
    cant: 1,
    name: 'Lina',
    middlename: 'Marcela',
    surname: 'Gomez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Ratona',
    gender: 'Girl',
    price: 165000,
    total: 165000,
    payment: 100000,
    debt: 65000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3147875770,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Cabeza, xapatos, color gris y rosa',
    progress: 0,
  },
  {
    id: 26,
    date: '26/09/2022',
    factNum: 538,
    cant: 1,
    name: 'Laura',
    middlename: 'Julia',
    surname: 'Sotelo',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Caperucita',
    gender: 'Girl',
    price: 140000,
    total: 140000,
    payment: 50000,
    debt: 90000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 314947282,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Capucha, CaP, Top, Falda, Delantal, Tutú, 3136206309',
    progress: 0,
  },
  {
    id: 27,
    date: '27/09/2022',
    factNum: 672,
    cant: 1,
    name: 'Oliver',
    middlename: 'undefined',
    surname: 'Sotelo',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Paisa',
    gender: 'Boy',
    price: 40000,
    total: 40000,
    payment: 40000,
    debt: 0,
    rentValue: 20000,
    returnDate: '29/09/2022',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3166858338,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description:
      'Machete, fusta, carriel, poncho, rabo de gallo, pantalon, camisa, sombrero ',
    progress: 0,
  },
  {
    id: 28,
    date: '27/09/2022',
    factNum: 673,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Franciscano',
    gender: 'Boy',
    price: 50000,
    total: 50000,
    payment: 50000,
    debt: 0,
    rentValue: 0,
    returnDate: '29/09/2022',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 0,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Capirote, cinturon, túnico',
    progress: 0,
  },
  {
    id: 29,
    date: '03/09/2022',
    factNum: 674,
    cant: 1,
    name: 'Ingrid',
    middlename: 'undefined',
    surname: 'Reyes',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Rockera',
    gender: 'Girl',
    price: 170000,
    total: 170000,
    payment: 100000,
    debt: 70000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3117344002,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 30,
    date: '09/09/2022',
    factNum: 704,
    cant: 1,
    name: 'Omar ',
    middlename: 'undefined',
    surname: 'Piamba ',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Mapalé',
    gender: 'Girl',
    price: 35000,
    total: 35000,
    payment: 35000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3229176799,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'Efectivo',
    description:
      'Omar de Jesus Piamba-maestro de construccion - diseño madera - 3226197623',
    progress: 0,
  },
  {
    id: 31,
    date: '09/09/2022',
    factNum: 706,
    cant: 1,
    name: 'Yadira',
    middlename: 'undefined',
    surname: 'Milan',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Soldado Antiguo',
    gender: 'Boy',
    price: 35000,
    total: 35000,
    payment: 35000,
    debt: 0,
    rentValue: 20000,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3205025827,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 32,
    date: '13/09/2022',
    factNum: 707,
    cant: 1,
    name: 'Edwin',
    middlename: 'undefined',
    surname: 'Guerrero',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Sirena',
    gender: 'Girl',
    price: 35000,
    total: 35000,
    payment: 35000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3216646086,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 33,
    date: '19/09/2022',
    factNum: 708,
    cant: 1,
    name: 'Lina',
    middlename: 'undefined',
    surname: 'Alegría',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Rockero',
    gender: 'Boy',
    price: 50000,
    total: 50000,
    payment: 50000,
    debt: 0,
    rentValue: 20000,
    returnDate: '29/09/2022',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3128343220,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: '3 piezas',
    progress: 0,
  },
  {
    id: 34,
    date: '27/09/2022',
    factNum: 710,
    cant: 1,
    name: 'Yerly',
    middlename: 'undefined',
    surname: 'Mamian',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Campesino',
    gender: 'Girl',
    price: 40000,
    total: 40000,
    payment: 40000,
    debt: 0,
    rentValue: 0,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3106928658,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: '4 cosas, no dejo deposito, gobernacion del cauca',
    progress: 0,
  },
  {
    id: 35,
    date: '29/09/2022',
    factNum: 711,
    cant: 1,
    name: 'Diana',
    middlename: 'undefined',
    surname: 'Tombé',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Oveja',
    gender: 'Boy',
    price: 35000,
    total: 35000,
    payment: 35000,
    debt: 0,
    rentValue: 15000,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3136221387,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Enterizo, cabeza, pantalon negro',
    progress: 0,
  },
  {
    id: 36,
    date: '30/09/2022',
    factNum: 712,
    cant: 1,
    name: 'Nino',
    middlename: 'undefined',
    surname: 'Bolaños',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Gato',
    gender: 'Boy',
    price: 30000,
    total: 30000,
    payment: 30000,
    debt: 0,
    rentValue: 20000,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 0,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'color gris',
    progress: 0,
  },
  {
    id: 38,
    date: '03/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'UVA',
    gender: 'Boy',
    price: 30000,
    total: 30000,
    payment: 0,
    debt: 30000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3114484858,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 40,
    date: '05/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'SAHUMADORA',
    gender: 'Girl',
    price: 50000,
    total: 50000,
    payment: 0,
    debt: 50000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3006536903,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'LLEVÓ EL 6',
    progress: 0,
  },
  {
    id: 41,
    date: '06/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'TRAJE CUMBIA?',
    gender: 'Girl',
    price: 30000,
    total: 30000,
    payment: 0,
    debt: 30000,
    rentValue: 10000,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3245694546,
    status: 'undefined',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 42,
    date: '07/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'TIBURON',
    gender: 'Boy',
    price: 35000,
    total: 35000,
    payment: 0,
    debt: 35000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3128131923,
    status: 'CANCELED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'SALDO PTE PA OCTUBRE',
    progress: 0,
  },
  {
    id: 43,
    date: '08/09/2022',
    factNum: 1,
    cant: 2,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'TRAJE 80s x2',
    gender: 'Boy',
    price: 50000,
    total: 100000,
    payment: 0,
    debt: 100000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3156892740,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 44,
    date: '09/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'ACCESORIO',
    costumeName: 'FALDA CUADROS',
    gender: 'Girl',
    price: 20000,
    total: 20000,
    payment: 0,
    debt: 20000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3127695761,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 45,
    date: '10/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'ARLEQUIN',
    gender: 'Boy',
    price: 0,
    total: 0,
    payment: 0,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3177897118,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'LLEVÓ EL 15',
    progress: 0,
  },
  {
    id: 46,
    date: '11/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'SOLDADO PLOMO ROJO',
    gender: 'Boy',
    price: 35000,
    total: 35000,
    payment: 0,
    debt: 35000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3238003352,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 47,
    date: '12/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'ABEJA',
    gender: 'Girl',
    price: 35000,
    total: 35000,
    payment: 0,
    debt: 35000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3002079843,
    status: 'RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 48,
    date: '13/09/2022',
    factNum: 1,
    cant: 1,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'CEREMONIAL',
    costumeName: '7 TRAJES 40K - 1 FALDA 15K',
    gender: 'Girl',
    price: 295000,
    total: 295000,
    payment: 200000,
    debt: 95000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3108849309,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 49,
    date: '14/09/2022',
    factNum: 1,
    cant: 3,
    name: 'undefined',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'CEREMONIAL',
    costumeName: '3 VESTIDOS',
    gender: 'Girl',
    price: 40000,
    total: 120000,
    payment: 0,
    debt: 120000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3235003583,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 50,
    date: '01/10/2022',
    factNum: 713,
    cant: 1,
    name: 'Yessica',
    middlename: 'undefined',
    surname: 'Llantén',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Peru',
    gender: 'Woman',
    price: 70000,
    total: 70000,
    payment: 70000,
    debt: 0,
    rentValue: 0,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3104347763,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Universidad antonio nariño, tercer semestre',
    progress: 0,
  },
  {
    id: 51,
    date: '01/10/2022',
    factNum: 713,
    cant: 1,
    name: 'Yessica',
    middlename: 'undefined',
    surname: 'Llantén',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Peru',
    gender: 'Man',
    price: 70000,
    total: 70000,
    payment: 70000,
    debt: 0,
    rentValue: 0,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3104347763,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Universidad antonio nariño, tercer semestre',
    progress: 0,
  },
  {
    id: 52,
    date: '03/10/2022',
    factNum: 539,
    cant: 1,
    name: 'Lady',
    middlename: 'undefined',
    surname: 'Montoya',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Superchica',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 100000,
    debt: 80000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '25/10/2022',
    size: 'undefined',
    phone: 0,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'Transferencia',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 53,
    date: '04/10/2022',
    factNum: 714,
    cant: 8,
    name: 'Julio',
    middlename: 'Cesar',
    surname: 'Urbano',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Niños Rojos',
    gender: 'Boy',
    price: 45000,
    total: 360000,
    payment: 100000,
    debt: 260000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3194602211,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Transferencia',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 54,
    date: '04/10/2022',
    factNum: 715,
    cant: 1,
    name: 'Angelica',
    middlename: 'undefined',
    surname: 'Solan',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Batichica',
    gender: 'Woman',
    price: 70000,
    total: 70000,
    payment: 25000,
    debt: 45000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3126584780,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 55,
    date: '04/10/2022',
    factNum: 715,
    cant: 1,
    name: 'Angelica',
    middlename: 'undefined',
    surname: 'Solan',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Mujer maravilla',
    gender: 'Woman',
    price: 70000,
    total: 70000,
    payment: 25000,
    debt: 45000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3126584780,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 56,
    date: '05/10/2022',
    factNum: 540,
    cant: 1,
    name: 'Julian',
    middlename: 'undefined',
    surname: 'Rivera',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Cocodrilo',
    gender: 'Boy',
    price: 160000,
    total: 160000,
    payment: 100000,
    debt: 60000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '31/10/2022',
    size: 'undefined',
    phone: 3156729660,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Transferencia',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 57,
    date: '05/10/2022',
    factNum: 541,
    cant: 1,
    name: 'Camilo',
    middlename: 'A',
    surname: 'Salazar',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Dama Antigua',
    gender: 'Girl',
    price: 170000,
    total: 170000,
    payment: 100000,
    debt: 70000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '31/10/2022',
    size: 'undefined',
    phone: 3206192339,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Enagua, tocado cabeza, vestido manga sisa, Gaban',
    progress: 0,
  },
  {
    id: 58,
    date: '05/10/2022',
    factNum: 675,
    cant: 1,
    name: 'Bethsabet',
    middlename: 'undefined',
    surname: 'Gomez',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Indio',
    gender: 'Boy',
    price: 50000,
    total: 50000,
    payment: 50000,
    debt: 0,
    rentValue: 10000,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3204894092,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 59,
    date: '06/10/2022',
    factNum: 676,
    cant: 1,
    name: 'Yeferson',
    middlename: ' alexis ',
    surname: 'salazar ',
    lastsurname: 'hurtado',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Cumbia',
    gender: 'Boy',
    price: 0,
    total: 0,
    payment: 0,
    debt: 0,
    rentValue: 15000,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 0,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'undefined',
    description: '1061807521,  Pinar de la vega casa 62',
    progress: 0,
  },
  {
    id: 60,
    date: '07/10/2022',
    factNum: 542,
    cant: 1,
    name: 'Tatiana ',
    middlename: 'undefined',
    surname: 'Ramos',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Raton',
    gender: 'Boy',
    price: 420000,
    total: 420000,
    payment: 200000,
    debt: 220000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '20/10/2022',
    size: 'undefined',
    phone: 3232858733,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: '8 MESES',
    progress: 0,
  },
  {
    id: 61,
    date: '09/10/2022',
    factNum: 543,
    cant: 6,
    name: 'Grupo Fenix',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Payaso',
    gender: 'Man',
    price: 166667,
    total: 1000002,
    payment: 1000002,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '########',
    size: 'undefined',
    phone: 3128518227,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 62,
    date: '09/10/2022',
    factNum: 544,
    cant: 1,
    name: 'JULIAN',
    middlename: 'undefined',
    surname: 'Valencia',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'Nariño',
    gender: 'Boy',
    price: 30000,
    total: 30000,
    payment: 30000,
    debt: 0,
    rentValue: 20000,
    returnDate: '########',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3145697408,
    status: 'NOT RETURNED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Bebe',
    progress: 0,
  },
  {
    id: 63,
    date: '10/10/2022',
    factNum: 467,
    cant: 1,
    name: 'Manedy',
    middlename: 'undefined',
    surname: 'Muñoz',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'Vestido',
    costumeName: 'Cola Pato',
    gender: 'Girl',
    price: 220000,
    total: 220000,
    payment: 220000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '20/11/2022',
    size: 'undefined',
    phone: 3135971210,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'vestido rojo, blanco cola pato, corona pincesa',
    progress: 0,
  },
  {
    id: 64,
    date: '10/10/2022',
    factNum: 468,
    cant: 1,
    name: 'Angelica',
    middlename: 'undefined',
    surname: 'Arteaga',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Mujer maravilla',
    gender: 'Girl',
    price: 160000,
    total: 160000,
    payment: 70000,
    debt: 90000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3106130259,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: '3 años, faltan puños, balaca, lazo,meter tutu falda',
    progress: 0,
  },
  {
    id: 65,
    date: '10/10/2022',
    factNum: 469,
    cant: 19,
    name: 'kukaramakara',
    middlename: 'undefined',
    surname: 'undefined',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Manicomio',
    gender: 'Man',
    price: 65000,
    total: 1235000,
    payment: 1000000,
    debt: 235000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '27/10/2022',
    size: 'undefined',
    phone: 3102294104,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 66,
    date: '11/10/2022',
    factNum: 470,
    cant: 7,
    name: 'Lilibeth',
    middlename: 'undefined',
    surname: 'Ramirez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'TRAJE TIPICO',
    costumeName: 'Huila',
    gender: 'Girl',
    price: 130714,
    total: 914998,
    payment: 914998,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3203604670,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Transferencia',
    description: 'Cambiar faldas',
    progress: 0,
  },
  {
    id: 67,
    date: '11/10/2022',
    factNum: 545,
    cant: 1,
    name: 'undefined',
    middlename: 'Leonardo',
    surname: 'Vallejo',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Mujer maravilla',
    gender: 'Girl',
    price: 140000,
    total: 140000,
    payment: 70000,
    debt: 70000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3117681782,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: '3 AÑOS, BALACAS, BRAZALETES',
    progress: 0,
  },
  {
    id: 68,
    date: '11/10/2022',
    factNum: 546,
    cant: 1,
    name: 'Yelitza',
    middlename: 'undefined',
    surname: 'Gomez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Michael Jackson',
    gender: 'Boy',
    price: 100000,
    total: 100000,
    payment: 70000,
    debt: 30000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 3113673660,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'brillante negro',
    progress: 0,
  },
  {
    id: 69,
    date: '11/10/2022',
    factNum: 471,
    cant: 1,
    name: 'Yaqueline',
    middlename: 'undefined',
    surname: 'Muñoz',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Picapiedra',
    gender: 'Girl',
    price: 120000,
    total: 120000,
    payment: 50000,
    debt: 70000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '20/10/2022',
    size: 'undefined',
    phone: 3146471370,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 70,
    date: '12/10/2022',
    factNum: 547,
    cant: 1,
    name: 'Yuriza',
    middlename: 'undefined',
    surname: 'Barrera',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Gokú Black',
    gender: 'Boy',
    price: 235000,
    total: 235000,
    payment: 50000,
    debt: 185000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 3113232940,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'opcional entrega 31 de octubre',
    progress: 0,
  },
  {
    id: 71,
    date: '13/10/2022',
    factNum: 548,
    cant: 1,
    name: 'Juan',
    middlename: 'undefined',
    surname: 'Hoyos',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Mario Bross',
    gender: 'Boy',
    price: 135000,
    total: 135000,
    payment: 50000,
    debt: 85000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3147152764,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'sin fecha de entrega',
    progress: 0,
  },
  {
    id: 72,
    date: '14/10/2022',
    factNum: 549,
    cant: 1,
    name: 'Fabian',
    middlename: 'undefined',
    surname: 'Bastidas',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Blanca Nieves',
    gender: 'Girl',
    price: 150000,
    total: 150000,
    payment: 50000,
    debt: 100000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3147578917,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'sin fecha de entrega',
    progress: 0,
  },
  {
    id: 73,
    date: '15/10/2022',
    factNum: 550,
    cant: 1,
    name: 'Vanessa',
    middlename: 'undefined',
    surname: 'Marin',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Spiderman',
    gender: 'Boy',
    price: 140000,
    total: 140000,
    payment: 100000,
    debt: 40000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 3214326849,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'Efectivo',
    description:
      'opcional entrega 31 de octubre, Forros de botas, Czap:44, Lzap:18, capa, gorro cabeza',
    progress: 0,
  },
  {
    id: 74,
    date: '15/10/2022',
    factNum: 472,
    cant: 1,
    name: 'Camilo ',
    middlename: 'undefined',
    surname: 'Ruiz',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Frozen',
    gender: 'Girl',
    price: 160000,
    total: 160000,
    payment: 160000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3058624349,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Colocar enagua, corona, arreglar capa y murano',
    progress: 0,
  },
  {
    id: 75,
    date: '19/08/2022',
    factNum: 527,
    cant: 1,
    name: 'LUCY',
    middlename: 'CAROLINA',
    surname: 'CASTILLO',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'SONIC',
    gender: 'Boy',
    price: 175000,
    total: 175000,
    payment: 100000,
    debt: 75000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '22/10/2022',
    size: 'undefined',
    phone: 3207930068,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'BOTAS, ENTERIZO,CAPUCHA',
    progress: 0,
  },
  {
    id: 76,
    date: '19/07/2022',
    factNum: 518,
    cant: 1,
    name: 'VANESA',
    middlename: 'undefined',
    surname: 'VALENCIA',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Murcielago, bella',
    gender: 'undefined',
    price: 165000,
    total: 165000,
    payment: 165000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '15/10/2022',
    size: 'undefined',
    phone: 3016657439,
    status: 'TO DO',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Son dos disfraces, faltan guantes de bella',
    progress: 90,
  },
  {
    id: 77,
    date: '19/10/2022',
    factNum: 725,
    cant: 2,
    name: 'Angie',
    middlename: 'undefined',
    surname: 'Cordoba',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Años 60',
    gender: 'Girl',
    price: 65000,
    total: 130000,
    payment: 130000,
    debt: 0,
    rentValue: 0,
    returnDate: '22/10/2022',
    deliveryDate: '20/10/2022',
    size: 'undefined',
    phone: 3173951124,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description:
      'https://coderunner86.sharepoint.com/:b:/s/TestCRM/EXN8oOTSfUhHun7kkqlcIz4BG0YZ1lpmsbl6HClM9T66ww?e=L8YWbb',
    progress: 0,
  },
  {
    id: 78,
    date: '29/08/2022',
    factNum: 528,
    cant: 1,
    name: 'yasmina',
    middlename: 'undefined',
    surname: 'estrada',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'reina de la naturaleza',
    gender: 'Woman',
    price: 300000,
    total: 300000,
    payment: 150000,
    debt: 150000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '28/10/2022',
    size: 'undefined',
    phone: 3128415863,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 79,
    date: '15/10/2022',
    factNum: 473,
    cant: 1,
    name: 'Alejandra',
    middlename: 'undefined',
    surname: 'Rodriguez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Batichica',
    gender: 'Girl',
    price: 190000,
    total: 190000,
    payment: 100000,
    debt: 90000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: '[{"espalda":30,"pecho":62,"cintura":54,"largo_talle_delantero":35.40,"largo_talle_trasero":33,"largo_falda":28}]',
    phone: 3184399880,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'cuello dorado, manga dorada',
    progress: 80,
  },
  {
    id: 80,
    date: '21/10/2022',
    factNum: 474,
    cant: 1,
    name: 'Angela',
    middlename: 'undefined',
    surname: 'Gomez',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Bella',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 100000,
    debt: 80000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '30/10/2022',
    size: 'undefined',
    phone: 3104602692,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'faltan guantes',
    progress: 90,
  },
  {
    id: 81,
    date: '21/10/2022',
    factNum: 475,
    cant: 1,
    name: 'Dario',
    middlename: 'undefined',
    surname: 'bustamante',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Capa',
    gender: 'Man',
    price: 60000,
    total: 60000,
    payment: 60000,
    debt: 0,
    rentValue: 0,
    returnDate: '24/10/2022',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3205532089,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 100,
  },
  {
    id: 82,
    date: '22/10/2022',
    factNum: 476,
    cant: 4,
    name: 'lorena',
    middlename: 'undefined',
    surname: 'garcia',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'TRAJE TIPICO',
    costumeName: 'currulao',
    gender: 'undefined',
    price: 45000,
    total: 180000,
    payment: 0,
    debt: 180000,
    rentValue: 0,
    returnDate: '29/10/2022',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3215360909,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 80,
  },
  {
    id: 83,
    date: '22/10/2022',
    factNum: 477,
    cant: 1,
    name: 'jaciento',
    middlename: 'undefined',
    surname: 'oviedo',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'cenicienta',
    gender: 'Girl',
    price: 160000,
    total: 160000,
    payment: 160000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '28/10/2022',
    size: 'undefined',
    phone: 3007133535,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'undefined',
    description: 'undefined',
    progress: 80,
  },
  {
    id: 84,
    date: '22/10/2022',
    factNum: 478,
    cant: 1,
    name: 'angela',
    middlename: 'undefined',
    surname: 'molano',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'Caperucita',
    gender: 'Girl',
    price: 100000,
    total: 100000,
    payment: 100000,
    debt: 0,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '22/10/2022',
    size: '[{"espalda":36,"pecho":70,"cintura":62,"cadera":74,"largo_talle_delantero":28,"largo_manga":48,"largo_falda":36,"largo_capa:101,"largo_capucha:47}]',
    phone: 3015215777,
    status: 'DELIVERED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'YA LO LLEVÓ',
    progress: 100,
  },
  {
    id: 85,
    date: '22/10/2022',
    factNum: 480,
    cant: 1,
    name: 'Sandra ',
    middlename: 'undefined',
    surname: 'sandoval',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Dama Antigua',
    gender: 'Girl',
    price: 60000,
    total: 60000,
    payment: 20000,
    debt: 40000,
    rentValue: 0,
    returnDate: '########',
    deliveryDate: '27/10/2022',
    size: '[{"espalda":34,"pecho":63,"cintura":59.58,"cadera":75,"largo_talle_delantero":48,"largo_manga":45,"largo_falda":0,"largo_pantalon:70}]',
    phone: 3014161604,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Cambió espantapájaros por dama antigua',
    progress: 0,
  },
  {
    id: 86,
    date: '23/10/2022',
    factNum: 482,
    cant: 1,
    name: 'karen',
    middlename: 'undefined',
    surname: 'Meneses',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'superman ',
    gender: 'Boy',
    price: 165000,
    total: 165000,
    payment: 50000,
    debt: 115000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: '29/10/2022',
    size: 'undefined',
    phone: 3157710168,
    status: 'IN PROGRESS',
    image: 'undefined',
    paymentType: 'Efectivo',
    description:
      'Capa, enterizo musculoso, poner mas espuma en los brazos, botas, cinturón, se tomó dibujo de contrno de zapato',
    progress: 80,
  },
  {
    id: 87,
    date: '20/10/2022',
    factNum: 726,
    cant: 1,
    name: 'yenifer',
    middlename: 'undefined',
    surname: 'manzano',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'soldado de plomo',
    gender: 'Boy',
    price: 40000,
    total: 40000,
    payment: 40000,
    debt: 0,
    rentValue: 10000,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3104163036,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'revisar si se entregó o hay que acomodar',
    progress: 100,
  },
  {
    id: 88,
    date: '20/10/2022',
    factNum: 727,
    cant: 1,
    name: 'amparo ',
    middlename: 'undefined',
    surname: 'ceron',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'vampira',
    gender: 'Woman',
    price: 70000,
    total: 70000,
    payment: 70000,
    debt: 0,
    rentValue: 0,
    returnDate: '24/10/2022',
    deliveryDate: '20/10/2022',
    size: 'undefined',
    phone: 3006020238,
    status: 'DELIVERED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description:
      'Capa y vestido, se lleva un adicional para devolver en la mañana, no deja deposito',
    progress: 100,
  },
  {
    id: 89,
    date: '22/10/2022',
    factNum: 728,
    cant: 1,
    name: 'jaciento',
    middlename: 'undefined',
    surname: 'oviedo',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'pirata',
    gender: 'Boy',
    price: 50000,
    total: 50000,
    payment: 50000,
    debt: 0,
    rentValue: 0,
    returnDate: '29/10/2022',
    deliveryDate: '27/10/2022',
    size: 'undefined',
    phone: 3007133535,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 100,
  },
  {
    id: 90,
    date: '22/10/2022',
    factNum: 729,
    cant: 1,
    name: 'maria ',
    middlename: 'elena',
    surname: 'mosquera',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'arabe',
    gender: 'undefined',
    price: 60000,
    total: 60000,
    payment: 60000,
    debt: 0,
    rentValue: 20000,
    returnDate: '25/10/2022',
    deliveryDate: '22/10/2022',
    size: 'undefined',
    phone: 3148239705,
    status: 'DELIVERED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Colombo frances, 7B, preguntar',
    progress: 100,
  },
  {
    id: 91,
    date: '22/10/2022',
    factNum: 730,
    cant: 1,
    name: 'carlos',
    middlename: 'undefined',
    surname: 'Lopez',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'guason',
    gender: 'Boy',
    price: 80000,
    total: 80000,
    payment: 40000,
    debt: 40000,
    rentValue: 0,
    returnDate: '30/10/2022',
    deliveryDate: '27/10/2022',
    size: 'undefined',
    phone: 3222668167,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Camisa, pantalon, chaleco, gaban',
    progress: 80,
  },
  {
    id: 92,
    date: '22/10/2022',
    factNum: 731,
    cant: 1,
    name: 'ingrid',
    middlename: 'undefined',
    surname: 'astudillo',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'jazmin',
    gender: 'Girl',
    price: 70000,
    total: 70000,
    payment: 55000,
    debt: 15000,
    rentValue: 0,
    returnDate: '########',
    deliveryDate: '29/10/2022',
    size: 'undefined',
    phone: 3135963930,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 80,
  },
  {
    id: 93,
    date: '24/10/2022',
    factNum: 732,
    cant: 1,
    name: 'dayana',
    middlename: 'undefined',
    surname: 'hidalgo',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'BLANCA NIEVES',
    gender: 'Girl',
    price: 85000,
    total: 85000,
    payment: 40000,
    debt: 45000,
    rentValue: 0,
    returnDate: '########',
    deliveryDate: '29/10/2022',
    size: 'undefined',
    phone: 3113896592,
    status: 'ACCOMMODATE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'Capa, liston, moño, enagua, vestido',
    progress: 80,
  },
  {
    id: 94,
    date: '24/10/2022',
    factNum: 733,
    cant: 1,
    name: 'carolina',
    middlename: 'undefined',
    surname: 'ortega',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'granjita con trencitas',
    gender: 'Girl',
    price: 180000,
    total: 180000,
    payment: 0,
    debt: 180000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3173706404,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 0,
  },
  {
    id: 95,
    date: '24/10/2022',
    factNum: 733,
    cant: 1,
    name: 'carolina',
    middlename: 'undefined',
    surname: 'ortega',
    lastsurname: 'undefined',
    category: 'VENTA',
    type: 'DISFRAZ',
    costumeName: 'tutu',
    gender: 'Girl',
    price: 120000,
    total: 120000,
    payment: 0,
    debt: 120000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3173706404,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'talla s',
    progress: 0,
  },
  {
    id: 96,
    date: '24/10/2022',
    factNum: 733,
    cant: 4,
    name: 'carolina',
    middlename: 'undefined',
    surname: 'ortega',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'capa',
    gender: 'Girl',
    price: 60000,
    total: 240000,
    payment: 0,
    debt: 240000,
    rentValue: 0,
    returnDate: 'undefined',
    deliveryDate: 'undefined',
    size: 'undefined',
    phone: 3173706404,
    status: 'DONE',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'alquiler',
    progress: 0,
  },
  {
    id: 97,
    date: '24/10/2022',
    factNum: 734,
    cant: 2,
    name: 'beatriz',
    middlename: 'undefined',
    surname: 'solano',
    lastsurname: 'undefined',
    category: 'ALQUILER',
    type: 'DISFRAZ',
    costumeName: 'Años 60',
    gender: 'undefined',
    price: 70000,
    total: 140000,
    payment: 140000,
    debt: 0,
    rentValue: 50000,
    returnDate: '27/10/2022',
    deliveryDate: '24/10/2022',
    size: 'undefined',
    phone: 3157760571,
    status: 'DELIVERED',
    image: 'undefined',
    paymentType: 'Efectivo',
    description: 'undefined',
    progress: 100,
  },
];
